### ISSUE TITLE
Conditional Peek() Methods

### ISSUE THREAD

**Issue by nathanila** [amaembo/streamex#107]
I've run into this situation a couple of times.

StreamEx.
   ...
   peek(item -> condition(item) ? doSomething(item) : doSomethingElse(item)).
   ...

Many times doSomethingElse() is simply {}.

Can you add methods such as the following?

peek(Predicate<? super T> condition, Consumer<? super T> action);
peek(Predicate<? super T> condition, Consumer<? super T> positive, Consumer<? super T> negative);

**Comment by amaembo** [comment]
Hello! Thank you for suggestion.

I don't think that usefulness of such change will outweigh the additional library complexity. Don't forget that I have IntStreamEx.peek, LongStreamEx.peek, DoubleStreamEx.peek, StreamEx.peek, EntryStream.peek and EntryStream.peekKeyValue, so for consistency all of them should probably be updated. Also why stopping on peek? Why not adding `map(Predicate, Function fnIfTrue, Function fnIfFalse)`? This would add a ton of additional operations. Also somebody would want something like this: `<TT> peek(Class<TT> clazz, Consumer<TT> consumer)` to apply the consumer only to stream elements which are instances of given class (like `e -> {if(e instanceof TT) consumer.accept((TT)e);}`).

Your problem can be easily solved in your code. Simply create utility class:

    public class FuncUtils {
        public static <T> Consumer<T> cond(Predicate<? super T> condition, 
                       Consumer<? super T> action) {
            return t -> {
                if(condition.test(t)) action.accept(t);
            }
        }

        public static <T> Consumer<T> cond(Predicate<? super T> condition, 
                       Consumer<? super T> positive, Consumer<? super T> negative) {
            return t -> {
                if(condition.test(t)) positive.accept(t); else negative.accept(t);
            }
        }
    }

After that `import static mypackage.FuncUtils.*`, then use `peek(cond(this::condition, this::doSomething, this::doSomethingElse))`. Similarly you can add such utility function combinators when you need something else (for example, three-arg map or peek which applies for elements of given class only). But I cannot add them all to the library, because there are simply too many combinations.
