### ISSUE TITLE
Documentation of cross() is misleading

### ISSUE THREAD

**Issue by wafisher** [amaembo/streamex#110]
I read the following documentation

```Perform cross product of current stream with given array, `Collection` or `Stream` source creating entries```

to mean that you could pass in a stream to `cross()`. I'm not sure what a `Stream` source is (a `Function` that generates a `Stream`?) but it seems natural to pass a `Stream` directly into `cross()`, hence the confusion.

The following code does not actually do a cross product but it seems natural that it would.

`StreamEx.of(1, 2, 3).cross(StreamEx.of(4, 5, 6))`

This only produces three values.

Please close if you disagree with my intuition.

**Comment by amaembo** [comment]
Hello! Thank you for your report.

I guess you are reading CHEATSHEET.md (it's always helpful to add a direct link to the page where you read the confusing documentation). Your problem can be easily solved using array/`Collection` version like this:

`StreamEx.of(1, 2, 3).cross(4, 5, 6)`
or
`StreamEx.of(1, 2, 3).cross(Arrays.asList(4, 5, 6))`

As for why crossing with Stream works differently: that's because streams are once-off. We need to read the passed stream several times (as many as size of the current stream). But you cannot read the same stream several times, so `StreamEx.of(1, 2, 3).cross(StreamEx.of(4, 5, 6))` cannot work unless I first save the passed stream into intermediate array or list which would require additional memory and may be unexpected. That's why you should provide instead a function which can generate a stream on demand like this: `StreamEx.of(1, 2, 3).cross(k -> StreamEx.of(4, 5, 6))`. This also adds a flexibility as you can use `k` (current value of the left stream) and produce different streams every time (for example, `StreamEx.of(1, 2, 3).cross(k -> StreamEx.of(k+1, k+2, k+3))`.

The CHEATSHEET.md is aimed to be the short introduction to the library, so user can quickly learn all the features. It may be simplified in a number of places. The more complete description is always available in [longer javadoc](http://amaembo.github.io/streamex/javadoc/one/util/streamex/StreamEx.html#cross-java.util.function.Function-).

If you have an idea how to change CHEATSHEET.md to make it more correct while keeping simple, please share your idea with me.

**Comment by wafisher** [comment]
Thank you for the detailed response. Makes sense. Two points:

1. Assuming you don't want to change it, perhaps the cheatsheet (or even the Javadoc's) should be a little clearer about how using a `Stream` in `cross()` doesn't produce the _expected_ behavior. All I'm saying is I would have definitely guessed you could put a `Stream` into `cross()`. Just my intuition.

2. Maybe you _should_ store `List`? A cross product is so obviously non-linear that clients may well assume a `List` is being generated. I'd personally much rather that behavior (and that it were documented in the Javadoc) than the current one.

Thanks!

**Comment by amaembo** [comment]
If you already have two StreamEx objects and want to cross them, you can easily do `stream1.cross(stream2.toList())`. This adds only 9 characters, but makes your intention clear "yes, I want to produce intermediate list, I understand that it will take additional memory". Streams are lazy by their concept, so I don't like adding methods which will unexpectedly consume the stream. You can always consume it explicitly by yourself.

In many cases you already have a collection, so you don't need to do `StreamEx.of(collection1).cross(collection2.stream())`, you just can `StreamEx.of(collection1).cross(collection2)`.

**Comment by wafisher** [comment]
Makes sense. Anyhow it's your API so you should do what's best. Just wanted to give you the perspective of a single user. Closing this now!
