### ISSUE TITLE
takeUntil() and takeUntilInclusive()

### ISSUE THREAD

**Issue by nathanila** [amaembo/streamex#124]
AbstractStream has takeWhile() and takeWhileInclusive().  Both methods accept a Predicate.  What if I want to take until the Predicate is true?  Sure, I could negate the Predicate.  But, then I can't use a method reference and performance will be a little worse.

For example, let's say I want to iterate starting with some class and then continue until I reach a specific super class.  I could implement this using takeWhile().  Here's the code...

```
StreamEx.
   <Class<?>>iterate(someClass, Objects::nonNull, Class::getSuperclass).
   takeWhile(item -> !BaseClass.class.equals(item)).
   ...
```

With takeUntil(), I could implement this using a method reference.

```
StreamEx.
   <Class<?>>iterate(someClass, Objects::nonNull, Class::getSuperclass).
   takeUntil(BaseClass.class::equals).
   ...
```

**Comment by amaembo** [comment]
In general I don't like this proposal (there should be a border between "rich" and "bloated" API), but I'll leave it open. Probably I will change the opinion in future.

> But, then I can't use a method reference and performance will be a little worse.

It's actually a myth. In your particular case lambda `item -> !BaseClass.class.equals(item)` is faster than `BaseClass.class::equals`, because lambda don't capture any variables and could be bound to constant method handle, so the instance of lambda runtime representation will be created only once. On the other hand, method reference captures the class literal, thus it will be bound to factory method handle creating new instance of runtime representation every time this code executes. Never do any assumptions about performance without proper measurements. Method reference *usually* makes your class file a little shorter (a matter of ~50-100 bytes probably), but it is not "faster than lambda" in runtime, as some people think.

**Comment by wafisher** [comment]
I have to add my two cents here. I don't care about the performance ramifications but the semantics of a `dropUntil()` function make things so much more readable. It reads like an English sentence: "drop stream entries until <predicate evaluates to true>" i.e. "drop stream entries until X happens". This is a lot more readable than "take things while X doesn't happen".

Another big advantage is that with code completion in IntelliJ (and who _isn't_ using IntelliJ), the natural function to search for here is "drop" not "take". It's the immediate association with the high-level action. But honestly it's worth it for the readability boost alone.

**Comment by amaembo** [comment]
Given that Java 11 added a `Predicate.not` static method, now you can write `takeWhile(not(BaseClass.class::equals))` using method reference. Taking into account this, as well the fact that `takeWhile` is used not very often, I think it worth adding 12 new methods (Abstract/Int/Long/Double)StreamEx * (takeWhile/takeWhileInclusive/dropWhile) to the API.
