### ISSUE TITLE
Streams for primitive arrays

### ISSUE THREAD

**Issue by orionll** [amaembo/streamex#136]
As far as I know, there is no short way to get ```StreamEx<Character>``` for a char array (and other primitive arrays). Is there a plan to add methods for this?

**Comment by amaembo** [comment]
No, there are no such plans. Note that for char/byte/short `IntStream` is what you actually want (as for most of intermediate calculations and comparisons the type is widened to int). The problems occur when you want to construct and collect such stream. There are plenty of operations in StreamEx library to support this. E.g.:

- `IntStreamEx.of(char[])` - construct from `char[]` array
- `IntStreamEx.of(char[], int, int)` - construct from a slice of `char[]` array
- `IntStreamEx.ofChars(CharSequence)` - construct from `CharSequence`
- `IntStreamEx.toCharArray()` - collect into `char[]` array
- `IntStreamEx.charsToString()` - collect into `String`

Having these you can quite comfortably use `IntStreamEx` to represent a stream of chars.

Finally note that it's preferred to work with codepoints instead of chars to correctly handle surrogate pairs. This is also supported by `IntStreamEx`.

**Comment by orionll** [comment]
What about StreamEx<Boolean>?

**Comment by amaembo** [comment]
This is even rarely useful. Some scenarios could be covered by `IntStreamEx.of(BitSet)` (think of `BitSet` as stream of true/false bits) and `MoreCollectors.toBooleanArray(Predicate)`. If you have some specific problem which is not covered by existing functionality, let me know. Note that even if you really really need a stream of booleans, having `Boolean` boxed is not a big deal as this does not lead to memory allocation (`Boolean.valueOf(boolean)` just returns one of two predefined instances - either `Boolean.TRUE` or `Boolean.FALSE`). So using `StreamEx<Boolean>` instead of hypothetical specialized `BooleanStreamEx` will unlikely to add a big performance boost. Well, some operations like `distinct()` or `sorted()` for booleans could be specially optimized, but really, who needs them? I believe, almost every boolean stream could be rewritten without having boolean. For example

`StreamEx.of(data).mapToBoolean(x -> x.test(blahblah)).and()` -> `StreamEx.of(data).allMatch(x -> x.test(blahblah))`
`StreamEx.of(data).mapToBoolean(x -> x.test(blahblah)).or()` -> `StreamEx.of(data).anyMatch(x -> x.test(blahblah))`
`StreamEx.of(data).mapToBoolean(x -> x.test(blahblah)).mapToInt(b -> b ? 1 : 0).sum()` -> `StreamEx.of(data).filter(x -> x.test(blahblah)).count()`

**Comment by orionll** [comment]
```
boolean[] array = {true, false, true};

// Does the array have false?
System.out.println(StreamEx.of(array).has(false));

// Convert the array to string
System.out.println(StreamEx.of(array).join(","));
```

**Comment by amaembo** [comment]
Not much longer with current API:

```java
// Does the array have false?
IntStreamEx.range(array.length).anyMatch(idx -> array[idx]);

// Convert the array to string
IntStreamEx.range(array.length).mapToObj(idx -> String.valueOf(array[idx])).joining(", ");
```

**Comment by orionll** [comment]
> Not much longer with current API:

![How about no](https://dl.dropboxusercontent.com/u/28465211/How_about_no.jpg)
