### ISSUE TITLE
StreamEx.of(Collection...) to StreamEx.of(Iterable...)

### ISSUE THREAD

**Issue by nathanila** [amaembo/streamex#146]
I recommend you change the signature of StreamEx.of() from...

`public static <T> StreamEx<T> of(Collection<? extends T> collection)`

...to...

`public static <T> StreamEx<T> of(Iterable<? extends T> collection)`

I figure this is 100% backwards compatible and allows for additional inputs.

**Comment by amaembo** [comment]
Unfortunately it's not backwards compatible. For example, `StreamEx.of(entryStream)` will become ambiguous after this change (as `EntryStream` extends both `Stream` and `Iterable`). 

I personally don't like adding `Iterable` as input to StreamEx API methods. One reason besides compatibility is clarity of what's going on. Currently `StreamEx.of(collection)` is based on collection spliterator which is usually moreless nicely implemented (in particular parallelizes well). However, the `Iterable` default spliterator is quite bad: it's unordered and its parallelization capabilities is very poor. When you use `StreamEx.of(iterable.iterator())` I create my own spliterator which is ordered and parallelizes much better. So if we had `StreamEx.of(iterable)` method, it would be not clear what is actually used as source. For best performance I should have use `spliterator()` if passed iterable is a `Collection` and `iterator()` otherwise. However it's possible that your custom iterable (which is not `Collection`) has even better customly implemented `spliterator()` (for example which reports SIZED allowing some operations to be optimized). So currently you can explicitly write `StreamEx.of(iterable.iterator())` or `StreamEx.of(iterable.spliterator())` controlling what is used as actual stream source. Had we dedicated `StreamEx.of(iterable)` method, people would use it not thinking about performance.

Thus I suggest to write explicitly `StreamEx.of(iterable.iterator())` or `StreamEx.of(iterable.spliterator())` (if you know that your particular iterable has good spliterator). It's not that longer. If it really bothers you, you can always create a static method in some utility class of your project like this:

```java
class StreamUtils {
  public static <T> StreamEx<T> of(Iterable<T> iterable) {
    return StreamEx.of(iterable.iterator());
  }
}
```

**Comment by nathanila** [comment]
Thank you for taking the time to explain the details.  I definitely agree with your thinking.  Keep up the great work!

**Comment by szarnekow** [comment]
In our projects, we have a few cases where we make extensive use of Iterables (for historic reasons, as usual). Nowadays this would have been done differently, but it is what it is. Along with the Iterables on APIs, a lot of client code exists which uses Guava Iterables or FluentIterable on top of that.
It would be great if such code could be easily refactored towards StreamEx as the driver to process the data. I can probably live with the suggested `StreamEx.of(iterable.(spl)?iterator())` for the initial creating of the stream. What is not super nice is the lack of an equivalent to `flatCollection` for iterables. 
Hypothetically: Would you consider an API `StreamEx.ofIterable(..)` which clearly states that it'll take the `spliterator()` to prime the `StreamEx` and `flatIterable` also with a kind-of bold hint on the docs?
