### ISSUE TITLE
Append/Prepend with suppliers

### ISSUE THREAD

**Issue by buckelieg** [amaembo/streamex#152]
Add append/prepend methods with java.util.Supplier<T> as an argument thus we could provide element construction.
streamex.prepend(() -> {/*construct element here*/});

Currently workaround is used:
stream()
.prepend(
Optional.<T>empty().orElseGet(() -> {
                                                    T obj = new T();
                                                    obj.set...();
                                                    .....
                                                    return obj;
                                                }
                    )
)

**Comment by landawn** [comment]
Probably the better solution is add below utility method to your tool kit:

```java
public <T> T get(final Supplier<? extends T> supplier) {
      return supplier.get();
}
```
Then
```java
streamex.prepend(get(() -> {/construct element here/}));
```

**Comment by amaembo** [comment]
This does not add a value to the API as it does not produce any additional kind of laziness. If I will add such a feature, I will need to add supplier version to every single API call. Also this adds an additional overload, thus ambiguity. What if somebody already has a StreamEx of Suppliers? Then existing code may not compile anymore.

Since Java 1.0 there's a solution: if you want to execute several expressions in a row, extract them to the separate method. If you want an inline solution, you can write `((Supplier<T>)(() -> doWhatEverYouWant)).get()` or use the helper method proposed by @landawn.
