### ISSUE TITLE
EntryStream intermediate grouping (non-adjacent keys collapse)

### ISSUE THREAD

**Issue by mmariotti** [amaembo/streamex#153]
Hello,
I'd like to have a (quasi-)intermediate method to group by key without the adjacency requirement.
Currently I'm either sorting-then-collapsing, if possible, or splitting the flow to an intermediate Map:

```java
// this code is untested

private static Map<ManagedType<?>, Set<Attribute<?, ?>>> getAttributes(
	Set<ManagedType<?>> managedTypes,
	Map<ManagedType<?>, Set<Attribute<?, ?>>> declaredAttributes)
{
	Map<ManagedType<?>, Set<Attribute<?, ?>>> attributes = StreamEx.of(managedTypes)
		.cross(managedTypes)
		.filterKeyValue((k, v) -> v.getJavaType().isAssignableFrom(k.getJavaType()))
		.flatMapValues(v -> StreamEx.of(declaredAttributes.get(v)))
		.sortedBy(x -> x.getKey().getJavaType().getName())
		.collapseKeys(Collectors.toSet())
		.peekKeyValue((k, v) -> v.add(new ClassAttribute<>(k)))
		.mapValues(Collections::unmodifiableSet)
		.toImmutableMap();
		
	return attributes;
}


private static Map<ManagedType<?>, Set<Attribute<?, ?>>> getAttributes(
	Set<ManagedType<?>> managedTypes,
	Map<ManagedType<?>, Set<Attribute<?, ?>>> declaredAttributes)
{
	Map<ManagedType<?>, HashSet<Attribute<?, ?>>> intermediate = StreamEx.of(managedTypes)
		.cross(managedTypes)
		.filterKeyValue((k, v) -> v.getJavaType().isAssignableFrom(k.getJavaType()))
		.flatMapValues(v -> StreamEx.of(declaredAttributes.get(v)))
		.groupingTo(HashSet::new);

	Map<ManagedType<?>, Set<Attribute<?, ?>>> attributes = EntryStream.of(intermediate)
		.peekKeyValue((k, v) -> v.add(new ClassAttribute<>(k)))
		.mapValues(Collections::unmodifiableSet)
		.toImmutableMap();

	return attributes;
}
```

Anyway, Is there a better approach?

Thank you

**Comment by landawn** [comment]
Not sure if this satisfy your request.

```java
StreamEx.of(managedTypes)
	.cross(managedTypes)
	.filterKeyValue((k, v) -> v.getJavaType().isAssignableFrom(k.getJavaType()))
	.flatMapValues(v -> StreamEx.of(declaredAttributes.get(v)))
	.sortedBy(x -> x.getKey().getJavaType().getName())
	.collect(Collectors.collectingAndThen(Collectors.groupingBy(e -> e.getKey(), Collectors.toSet()), EntryStream::of))
	.peekKeyValue((k, v) -> v.add(new ClassAttribute<>(k)))
	.mapValues(Collections::unmodifiableSet)
	.toImmutableMap();	

```

**Comment by landawn** [comment]
I forked and made the changes to support intermediate at [landawn/streamex](https://github.com/landawn/streamex), welcome to take a try.
```java
StreamEx.of(managedTypes)
	.cross(managedTypes)
	.filter((k, v) -> v.getJavaType().isAssignableFrom(k.getJavaType()))
	.flatMapValues(v -> StreamEx.of(declaredAttributes.get(v)))
	.sortedByKey(k -> k.getJavaType().getName())
	.groupBy(Collectors.toSet())
	.peek((k, v) -> v.add(new ClassAttribute<>(k)))
	.mapValues(Collections::unmodifiableSet)
	.toImmutableMap();
```

**Comment by mmariotti** [comment]
Thank you for your effort :)

Neverthess I see a big drawback in your implementation: the stream is consumed in an (quasi-)intermediate operation.
This contradicts the expected stream "lazyness", where it is only consumed by `terminal` methods. I suppose this may also lead to concurrency issues on parallel streams, since the critical section has to be partitioned in at least two blocks.

However, I'm not sure it's even possible to apply a group operation on a stream without actually consuming it...

Anyway, thank you!

**Comment by amaembo** [comment]
I deliberately don't plan to add intermediate-looking operations which will actually consume the whole stream content. The only exception currently is `sorted()`-like operations, because `sorted()` is present in original Stream API as well. In any case to implement such feature you will need to store an intermediate Map containing all the keys and values. The code becomes more readable if this is explicitly done, like in your second sample.

If you definitely want to write everything in the single expression, you can use `chain` method:

`StreamEx.of(managedTypes)....chain(s -> EntryStream.of(s.groupingTo(HashSet::new)))...`

You can even extract it to the static method in your project:

```java
private static <K, V> Function<EntryStream<K, V>, EntryStream<K, Set<V>>> grouping() {
    return s -> EntryStream.of(s.groupingTo(HashSet::new));
}
```

And use simply `.chain(grouping())` which is exactly the same as @landawn did. However this will not be added to library as it hides the fact that the stream is consumed. This is not even quasi-intermediate operation, according to my definition of quasi-intermediate operations.

Personally I think that your second solution is the better way as it's more explicit and easier to debug. Intermediate sorting usually slower than intermediate grouping, according to my experience.
