### ISSUE TITLE
New updates

### ISSUE THREAD

**Issue by landawn** [amaembo/streamex#157]
Anyone continue to maintain this repository? I have made a few [changes](https://github.com/landawn/streamex/blob/master/CHANGES.md): but don't know how to commit.(BTW,This is a great project made by @amaembo. I really like it and recommended it to a lot of people, and that's why I made those changes to continue to improve it. Anyone who like the changes can go [landawn/streamex](https://github.com/landawn/streamex) to download the new version. just in case these changes can't be committed to trunk and release in time)

**Comment by amaembo** [comment]
Yes, the repository is still maintained by me. I accidentally had notifications switched off, that's why some questions went unanswerred. 

Most of your changes contradict with the concept of my library, so I would not accept them. Of course, you are free to maintain your own fork, but as it has many renamings anyways, it becomes highly incompatible with original StreamEx. In order to avoid confusion I would politely ask you to rename the project and the main package (anyways you've renamed many things already). Thanks.
