### ISSUE TITLE
Add shorten form toMap() by keys

### ISSUE THREAD

**Issue by radistao** [amaembo/streamex#167]
#### Actual:
[`toMap()`](https://github.com/amaembo/streamex/blob/5b1e4794f495d21c833bf944b401bb4934e755b9/src/main/java/one/util/streamex/StreamEx.java#L930) is overloaded to have shorten form if key is expected to be an element itself.

In the same time having opposite implementation (when key is mapped, and value is element itself) is also popular (in my experience key mapping even more popular).

#### Proposition:

Implement `toMap(Function keyMapper)` method to support shorten key-mapped maps.

#### Implementation notes:

Since both key-mapped and value-mapped functions have the same signature (single _Function_ argument) it is not possible (and even not recommended) to make additional `toMap` function. Instead of that i propose:
  - call new function smth like `toMapByKey(Function<? super T, ? extends K> keyMapper)` (or smth similar)
  - to avoid ambiguity or customers confusing - implement `toMapByValue(Function<? super T, ? extends V> valMapper)` function, which works absolutely the same as `toMap(Function<? super T, ? extends V> valMapper)` now.
  - mark obsolete `toMap(Function<? super T, ? extends V> valMapper)` as deprecated, referring to use new `toMapByValue` name.

WDYT?

**Comment by amaembo** [comment]
In general I don't like this suggestion. Yes, it was probably mistake to make an valMapper-only overload instead of keyMapper-only. But what's done that's done. This overload is simple shortcut over `toMap(keyMapper, x->x);` and typing extra `, x->x` is not that hard. Proposed alternatives `toMapByKey` and `toMapByValue` will not make code shorter. Thus this does not seem to be a good reason to mark `toMap(valMapper)` as deprecated. People don't like deprecated stuff, this produces compilation warnings here and there and may even break builds as some projects use fail-or-warning setting. Deprecation has high impact and I don't believe that it pays off here.
