### ISSUE TITLE
flatMap overloads for collections, arrays

### ISSUE THREAD

**Issue by primislas** [amaembo/streamex#170]
Hey,

I tried to search through issues and I don't think this one has been asked yet. Considering that default flatMap is only applicable to streams, it seems to me perfectly reasonable to overload flatMap for collections (and arrays) to call stream() under the hood to reduce boilerplate. I know there's a flatCollection(), but wondering if there's a good reason I'm missing for not adding this behavior to flatMap directly? It would make the code look even neater imo.

**Comment by amaembo** [comment]
flatMap(Function) is defined in the Stream interface. In Java you cannot create overloads with different argument types but having the same erasure.

**Comment by primislas** [comment]
Facepalm, true. I sometimes bypass erasure by declaring specific types though. E.g. I remember tinkering with various MyClassSupplier interfaces. For example, instead of Function<T,R> we could try declaring an
```
interface CollectionFunction<T,R> {
  Collection<R> apply(T t); 
}
```
Have you tried such an approach? If not, I could tinker to see if it's feasible and if it doesn't cause ambiguities as long as you aren't opposed to doing flatMap(collection) on principle.

**Comment by amaembo** [comment]
This would produce call-site ambiguities for every existing `flatMap` call as lambda disambuguation procedure does not take into account the return type. E.g. compiler cannot properly link calls `flatMap(x -> x.getStream())` or `flatMap(x -> x.getCollections())` to two target methods. In general it's a very bad idea to have two overloads which differs only in different functional interface argument. You will have many problems.

I think having `flatCollection` is a nice alternative. In general if you use streams extensively, your code should eventually become stream-minded. E.g. you should not have `Collection<User> getUsers()` in your API, instead you should have `Stream<User> users()`. Thus you will not need `groups.stream().flatMap(g -> g.getUsers().stream())`, use instead `groups.stream().flatMap(Group::users)`. Often people return collections/arrays from the methods just because they get used to it, but replacing them with streams may make the code better.
