### ISSUE TITLE
Add StreamEx.findOnly(Predicate)

### ISSUE THREAD

**Issue by krichter722** [amaembo/streamex#178]
It'd be nice to have a map function which asserts that the stream only contains exactly one element matching the search predicate and returns that element or throws an exception (`IllegalStateException` for example), i.e. throws the exception if the stream doesn't contain the element or if it contains more than one matching the predicate. I didn't figure out how to use this to allow a reduce operation afterwards, so I guess map and reduce take place in one step.

**Comment by amaembo** [comment]
Hello! 

There's a short-circuit collector called `onlyOne` which does the thing. See [javadoc] (http://amaembo.github.io/streamex/javadoc/one/util/streamex/MoreCollectors.html#onlyOne--). So you can do

```java
singleElement = streamex.collect(onlyOne()).orElseThrow(IllegalStateException::new);
```

Currently I don't like to add such method directly into StreamEx class, because a possibility to add a similar method was discussed recently in Java bug tracker (see [JDK-8201273](https://bugs.openjdk.java.net/browse/JDK-8201273)). So if there's a risk that two slightly incompatible methods will be added at the same time. In particular it's unclear whether zero case and 2+ case should be distinguishable.

**Comment by amaembo** [comment]
Hello! 

There's a short-circuit collector called `onlyOne` which does the thing. See [javadoc] (http://amaembo.github.io/streamex/javadoc/one/util/streamex/MoreCollectors.html#onlyOne--). So you can do

```java
singleElement = streamex.collect(onlyOne()).orElseThrow(IllegalStateException::new);
```

Currently I don't like to add such method directly into StreamEx class, because a possibility to add a similar method was discussed recently in Java bug tracker (see [JDK-8201273](https://bugs.openjdk.java.net/browse/JDK-8201273)). So if there's a risk that two slightly incompatible methods will be added at the same time. In particular it's unclear whether zero case and 2+ case should be distinguishable.

**Comment by krichter722** [comment]
Ah, thank you for the hint. Would you accept a PR linking that method in `findAny` and `findFirst` in one sentence?

**Comment by krichter722** [comment]
That doesn't check for a predicate, i.e. needs to be prefixed with `Stream.filter`. Afaik the above only checks that there's exactly one item in the stream. My idea was to provide a method which searches and asserts that the search result is exactly one.

**Comment by amaembo** [comment]
Well, I think we can add a trivial shortcut collector `onlyOne(Predicate)` -- see new issue #179.
