### ISSUE TITLE
mapIndexed and forEachIndexed

### ISSUE THREAD

**Issue by Meosit** [amaembo/streamex#217]
Is it possible to add the following methods to this library?
* `mapIndexed(BiFunction<E, Integer, U> mapper)`
* `forEachIndexed(BiConsumer<E, Integer> consumer)`

I personally find such methods very useful, but there are some concerns related to unordered collection, so it would be great to see what can be done to achieve that.

Thanks!

**Comment by amaembo** [comment]
Such an API is pretty limited and can blow up quickly. Next request would be `peekIndexed`, `filterIndexed`, `flatMapIndexed` and so on. Instead, we have an `EntryStream` that allows you to track value pairs and has a rich API to do everything you want. There are two ways to have indexed pairs:

1. If you have an array or list as a source (which is indexed by nature), use `EntryStream.of(list)` or `EntryStream.of(array)`. This will create `EntryStream<Integer, E>` and you can freely use all the EntryStream APIs like `mapKeyValue`, `filterKeyValue`, `forKeyValue` and so on. This stream is also nicely parallelizable.
2. Otherwise, if you already have StreamEx (should be pretty rare case in practice) you can use `streamEx.zipWith(IntStreamEx.ints())` and have `EntryStream<E, Integer>` (you can also use `.invert()` to transform it to `EntryStream<Integer, E>`). This stream has only limited parallelism.
