### ISSUE TITLE
Merge sort and limit operators

### ISSUE THREAD

**Issue by numeralnathan** [amaembo/streamex#228]
Let's say we have the following stream pattern...

    ...
    sorted().
    limit(k).
    ...

If the input has millions of rows, then the sort operation is going to do O(n log n) operations.  If the sort and limit operations were merged, then the sort operation only has to do O(n log k) operations.  If the smallest elements are encountered first, then the sort operation only has to do O(n + k log k) operations.

This could also reduce the memory usage from O(n) to O(k).

**Comment by amaembo** [comment]
I don't like doing this in StreamEx, because it will slightly change the behavior of limit() operation making it quasi-intermediate. If fixing this, it should be fixed on JDK level. I tried to fix this in JDK but wasn't enthusiastic enough to do this completely. See:
https://bugs.openjdk.java.net/browse/JDK-8153332
You can use MoreCollectors.greatest() and MoreCollectors.least(). These terminal operations already have this optimization.
