### ISSUE TITLE
Support for Gatherers

### ISSUE THREAD

**Issue by anantharaman93** [amaembo/streamex#272]
Hi.

I hope you might be aware of `Gatherers` feature that was proposed. [Reference 1](https://cr.openjdk.org/~vklang/Gatherers.html) [Reference 2](https://openjdk.org/jeps/461) .

Requesting support for similar functionality in this library.

Thanks.

**Comment by amaembo** [comment]
Hello!

It doesn't look like a good idea to mimic the API creating essentially a parallel class hierarchy. The concept of my library is to add reasonable operations inside the library itself, rather than providing a Gatherer-like mechanism to be able to extend it. I focus on practical needs, so if you miss a particular operation, feel free to report. Also note that using `headTail` operation, you can implement quite much of custom intermediate operation functionality without Gatherers.
