### ISSUE TITLE
skipLast(long n)

### ISSUE THREAD

**Issue by nathanila** [amaembo/streamex#58]
Please add `StreamEx.skipLast(long n)`.  This method is similar to `skip(long n)` except this method returns a stream consisting of the initial elements of this stream after discarding the last n elements of the stream.  If this stream contains fewer than n elements then an empty stream will be returned.

Here's an implementation.

    public static <T> Stream<T> skipLast(Stream<T> stream, int n)
    {
       Spliterator<T> iter;
       Stream<T> result;
 
       iter   = stream.spliterator();
       iter   = new SkipLast<>(iter, n);
       result = StreamSupport.stream(iter, false);
 
       return(result);
    }
 
    private static class SkipLast<T> extends Spliterators.AbstractSpliterator<T> implements Consumer<T>
    {
       private final Spliterator<T> m_input;
       private final ArrayDeque<T>  m_queue;
       private final int            m_n;
 
       public AllButLastN(Spliterator<T> input, int n)
       {
          super(Math.max(input.estimateSize() - n, 0), 0);
 
          m_input = input;
          m_n     = n;
          m_queue = new ArrayDeque<>(n + 1);
       }
 
       @Override
       public boolean tryAdvance(Consumer<? super T> action)
       {
          T value;
 
          while (m_queue.size() <= m_n)
             if (!m_input.tryAdvance(this))
                return(false);
 
          value = m_queue.pollFirst();
 
          action.accept(value);
 
          return(true);
       }
 
       @Override
       public void accept(T value)
       {
          m_queue.addLast(value);
       }
    }

**Comment by amaembo** [comment]
Thank you for the interest to my library. Unfortunately I don't like adding `skipLast`. The big problem is that it does not parallelize normally (well unless the source is SIZED/SUBSIZED). For features which cannot be parallelized there must be very strong reason to add them to the library. I have one such operation, namely `headTail`: it allows you to express almost every other intermediate operation within just a few lines. [Here](https://github.com/amaembo/streamex/commit/69bcfe81737156cd44ac081f23b9896b505410a4)'s the example which shows how to implement `skipLast` using `headTail` which is much shorter than your code. If you need such operation, just add the corresponding static method into your code. When #10 will be implemented you will even be able to chain this call:

    StreamEx.of(source).chain(s -> skipLast(s, n)).map(...) // do something else

I don't see that `skipLast` itself is useful enough to add it to the library directly. If your source is sized (collection, array, etc.), you may easily express it via `limit(collection.size()-n)` (which will be actually much more optimal as it will short-circuit and don't use intermediate memory). If you want to skip just one element, you can use existing `.mapLast(x -> null).nonNull()` (assuming that the original stream contains no `null` values, otherwise you can use some other special value). So there's actually very limited cases when `skipLast` is cannot be expressed using existing operations. And I haven't seen a real problem which would actually need this method.

Note that your implementation has a problem `skipLast(Stream.of(1,2,3), Integer.MAX_VALUE)` should return empty stream, but it will likely to die with `OutOfMemoryError`.

**Comment by nathanila** [comment]
Thank you for creating StreamEx!  It has a lot of utilities that I wished Java 8 Stream had.

 

Thank you for the example on how to use headTail().  I’m going to have to study it for a while to figure it out.  It seems to me that this is recursive.  Every time 1 element is taken from the stream a new StreamEx is created.  Yikes!  Do I understand this code correctly?  I suppose the recursive nature depends upon the implementation of headTail() itself.

 

Is chain() a method inside StreamEx or AbstractStreamEx?  I tried looking for it and didn’t find it in the source code or through Eclipse IDE method list.  I am wondering if this is on a private branch of yours.  I understand this method easily and it is powerful.  It means I can “extend” StreamEx with my own functionality.

 

My use case for skipLast() is for file rotation. I walk a tree of directories inside a Spliterator.  I then wrap it into a Stream.  I then filter out the files which are not log files.  I don’t need to sort the entire list of files since the directories are walked in creation order and the files in each directory are sorted.  At this point, I don’t have a count otherwise I could use limit().  I then want to keep the youngest N files.  These files are at the tail of the stream.  I can’t reverse the stream (and then skip()) since that would load all of the File objects into memory.

 

I am not seeing the OutOfMemoryError in my code.  The first call to tryAdvance() will spin in the loop 3 times and then return false because the input stream is exhausted.  Can you enlighten me?

 

-Nathan

**Comment by amaembo** [comment]
The `headTail()` method while looks recursive actually optimizes the recursion away automatically (when used properly). I currently perform many optimizations (see #57, #59) to reduce the allocations and overhead. With latest experimental optimizations `headTail()`-based operation takes in hot code ca 50-60 ns per element. To compare, computing like `"1234567".replaceAll("[123]", "")` takes around 500 ns, so if your pipeline contains non-trivial operations (especially involving I/O), `headTail()`-based op will not have significant overhead.

The `chain()` method is not implemented currently (see #10). However I'll likely to add it in the next release.

I understand your scenario. Note that it's not very hard to implement it in two passes (first pass to count files). This would even have constant memory allocation instead of O(N). Seems that you don't like it, right?

As for OOME, my mistake, try `skipLast(Stream.of(1,2,3), Integer.MAX_VALUE-1)`. The problem is that you preallocate `ArrayDeque` with supplied size even though it might be unnecessary.

**Comment by nathanila** [comment]
> The chain() method is not implemented currently (see #10). However I'll likely to add it in the next release.

 

Great!  I look forward to it.  This will allow for me to implement all sorts of new stream operators and not have to break up the stream into two pieces.

 

> The headTail() method while looks recursive actually optimizes the recursion away automatically (when used properly).

 

Amazing!  I guess I would have to really dig in to figure that out.

 

> I understand your scenario. Note that it's not very hard to implement it in two passes (first pass to count files). This would even have constant memory allocation instead of O(N). Seems that you don't like it, right?

 

Two passes means twice the I/O and one pass isn’t fast (i.e. minutes) when talking about millions of files.

 

In any case, headTail() (and chain()) are good enough to solve the problem.

 

> The problem is that you preallocate ArrayDeque with supplied size even though it might be unnecessary.

 

Good catch!  Thanks for pointing that out.

 

-Nathan

**Comment by amaembo** [comment]
The `chain()` method is committed to the master branch. Note that you can make it even more comfortable adding the helper method like this:

    public static <T> UnaryOperator<StreamEx<T>> skipLast(int n) {
        return stream -> skipLast(stream, n); // call the skipLast described above
    }

Now you can write `StreamEx.of(input).chain(skipLast(n)).forEach(System.out::println)`.

**Comment by nathanila** [comment]
Awesome!  Thanks for doing this!  Thanks for the tip on how to make it comfortable.

 

-Nathan
