### ISSUE TITLE
EntryStream.toMapAndThen()

### ISSUE THREAD

**Issue by nathanila** [amaembo/streamex#64]
`EntryStream` has a `toSetAndThen()` but not a `toMapAndThen()`.  Please add the following method.

    <R> EntryStream.toMapAndThen(Function<Map<K, V>, R> finisher)

**Comment by amaembo** [comment]
Well probably it's reasonable. The problem is that there are many signatures currently: `toMap()`, `toMap(mergeFunction)`, `toSortedMap()`, `toSortedMap(mergeFunction)`, `toCustomMap(supplier)`, `toCustomMap(mergeFunction, supplier)`. So the question is where to stop? Is `toMapAndThen(finisher)` enough or we should add `andThen` counterpart to every such signature? Also what about `groupingAndThen`? `joiningAndThen`? Most popular cases could be covered, but we cannot add a shortcut method for everything. Sometimes it's still better to have an intermediate variable.

**Comment by nathanila** [comment]
Yeah, there are a lot of map methods.  I asked because I know about the other to___AndThen() methods and wondered why toMapAndThen() is missing on EntryStream.  You are the API designer.  You need to figure out what is the appropriate boundary.

If these methods returned an Optional<Map>, then one could use Optional.map() to implement the to___AndThen() logic.

**Comment by amaembo** [comment]
The `EntryStream.toMapAndThen()` method is implemented.

**Comment by nathanila** [comment]
Thanks!
